### PR TITLE
upgrade migrations to django 1.8

### PR DESCRIPTION
**Pull request by muhammad-ammar**
TNL-3658

### CODE REVIEW

**Comment by muhammad-ammar** [comment]
@nedbat @doctoryes @symbolist @muzaffaryousaf @macdiesel @alawibaba Please review. Thanks!

**Comment by macdiesel** [comment]
:+1:

**Comment by doctoryes** [comment]
:+1:

**Comment by nedbat** [comment]
Isn't it too early to merge this into master?

**Comment by muhammad-ammar** [comment]
@nedbat I am not sure. Do you see any issues?

**Pull request merged**
